### PR TITLE
console.time() and timeEnd()

### PR DESCRIPTION
**Pull request by edwardball**
Hi Andy,

Here's another new secret : the console lets you start timers and then log the output.

Cheers,

Aptary

(PS I've not been sure about what to put in the "order" metadata at the top of the .md file, do you have a system you want me to keep to or do you just adjust these as you wish?)

### CODE REVIEW

**Comment by andismith** [comment]
Thank you for another tip.

I've been adding the order in myself. Essentially it's so they appear at the right point in the site.

The first part of order is for the section - so 05 is console

The second part for the order within console, so 00175 will likely be this one. Sorry, there's not really a concrete system. It's more how it feels best on the page.

So the order will likely be 05-00175 for this one.

**Comment by andismith** [comment]
This tip works in Firefox and Opera too. It works in Webkit Nightly - but appears broken in Safari 6.0.

**Comment by edwardball** [comment]
You're absolutely right, though it seems to work fine for me in Safari (v6.0.2).
I've made a new commit with the correct browsers.

**Comment by andismith** [comment]
Cool, thanks :+1:

**Pull request merged**
