### PR TITLE
Dock to right

### PR DESCRIPTION
**Pull request by iancrowther**
see commit comments

### CODE REVIEW

**Comment by andismith** [comment]
Hi Ian,

Thank you for contributing the secret. There's a secret called "Undock and Move the Developer Tools "already. Maybe it should be be renamed to "Move and Re-Dock the Developer Tools", and include the information you have posted here?

I'm trying to avoid adding too many secrets to do with docking, particularly as it's not _that_ hidden. For example, we could end up with a dock to bottom, undock in new window - and potentially a dock to left and dock to top in future browser releases. That would be 5 secrets based on docking.

What do you think? I'm open to suggestions. If there's a real need for a dock to right secret, I'm happy to add it. Just want to make sure it's for the right reasons.

Andy

**Comment by iancrowther** [comment]
Hey Andy,

You make some fair points and I agree that docking should be restricted to
a core secret with extras only for exceptions.

When developing mobile first with device overrides on, I feel that dock to
right is the perfect accompaniment and is a good candidate for a specific
secret.  I regularly get asked, "how did you get your dev tools to do
that". aka dock to right.  believe it or not, folks are still only just
coming to the mobile first way of thinking and this encourages them.

This could however be easily be resolved with a more targeted title, maybe
"Move Developer Tools for Mobile Layouts".  I understand that the last
thing you want is repetition and that you really want the killer features
to be highlighted, not the mundane ones so honestly its up too you.. I wont
get offended ;-)

**Comment by andismith** [comment]
Going to add Dock to Right, but re-word it slightly to make it reference responsive design.

**Comment by andismith** [comment]
Ok, it's live now as "Dock the Developer Tools to Aid Responsive Design". Thanks for submitting this Ian!

**Comment by iancrowther** [comment]
Great, thanks for the update. Your very welcome and fingers crossed the
site gains traction.

**Pull request merged**
